[package]
authors = ["Jason Housley <HousleyJK@gmail.com>"]
description = "Lightweight, event-driven WebSockets for Rust."
documentation = "https://ws-rs.org/docs"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"
name = "ws"
readme = "README.md"
repository = "https://github.com/housleyjk/ws-rs"
version = "0.5.3"

[dependencies]
bytes = "0.3.0"
httparse = "1.2.1"
log = "0.3.6"
mio = "0.6.1"
rand = "0.3.15"
sha1 = "0.2.0"
slab = "0.3.0"
url = "1.2.3"

[dependencies.libc]
optional = true
version = "0.2.18"

[dependencies.libz-sys]
optional = true
version = "1.0.7"

[dependencies.openssl]
optional = true
version = "0.7.14"

[dev-dependencies]
clap = "2.19.1"
env_logger = "0.3.5"
term = "0.4.4"
time = "0.1.35"

[features]
default = []
permessage-deflate = ["libz-sys", "libc"]
ssl = ["openssl"]
